### ISSUE TITLE
What is this project about?

### ISSUE THREAD

**Issue by jishnujayakumar** [OpenGenus/cosmos-search#1]

**Comment by AdiChat** [comment]
We are building a realtime search tool for Cosmos which will enable users to search for anything conveniently. The end goal is to extend this tool is provide Cosmos as an offline search tool.

This is in active development at our Slack community 😍

**Comment by jishnujayakumar** [comment]
What is Cosmos?

**Comment by AdiChat** [comment]
Cosmos is our knowledge base and this tool is different from existing tools in several aspects (one being it works offline). This is, clearly, evident through our end goal. Introductory discussions are mainly reserved for Slack. 👍

**Comment by Pl4gue** [comment]
@AdiChat  I would be interested in helping as well,  is this possible?

**Comment by nuhman** [comment]
@AdiChat why this repo is empty if development is already started in slack?

**Comment by AdiChat** [comment]
@Pl4gue Yes, we would love to have you in our team. I have send you an invite for Slack. 👍 

@nuhman This repository is empty because we have not decided to push our present work yet.

**Comment by sidmishraw** [comment]
@AdiChat Could I get an invite to the Slack channel 😄

**Comment by AdiChat** [comment]
Welcome @sidmishraw 🎉 I have send you an invite for Slack 👍
