### ISSUE TITLE
Add support for human-curated lists

### ISSUE THREAD

**Issue by AdiChat** [OpenGenus/cosmos-search#104]
**I'm submitting a:**  
- [ ] bug report
- [x] feature request

**Description**:

Create a template/ system to serve human-curated lists :book:.

The list will be in `json` formats and will contain a list of links along with title and description. There will be sub-sections and each sub-section will contain links. There may be several such lists. Consider a list for "best resources to learn Go" denoted by `learn_go.json` file. For this, sub-sections may be "websites", "youtube", "free tutorials", "paid courses" and others. 

The list must be available at `search.opengenus.org/list/learn_go`. In fact, it follows the following pattern: `search.opengenus.org/list/{list_name}`.

Sample JSON format:
```
{
	"title": "",
	"id": "",
	"tags": [],
	"link": "",
	"credit_link": "",
	"short_description": [],
	"long_description": [],
	"date": "",
	"authors": ["",""],
	"section": [
		{
			"sub_section": "",
			"id": "1.1",
			"short_description": "",
			"long_description": "",
			"tags": [],
			"grand_section": [
				{
					"title": "",
					"id": "1.1.1",
					"short_description": "",
					"long_description": "",
					"link": "",
					"tags" [],
				},
				...
			]
		},
		...
	]
}
```
You are free to use another `JSON` format as well. 

This includes creating a template and routing for such a sample list. From the UI point of view, the sub-sections must be presented to the user. When the user clicks on a sub-section title, it must expand and the contents must be visible. 

This will greatly enhance the user experience and reduce searching time by providing human curated links and knowledge. These lists will be presented as search results. This will form the basis for further exciting updates that will pave the way to a faster search. :+1:

**Comment by sakshee-19** [comment]
@AdiChat I would like to work on it.

**Comment by AdiChat** [comment]
Sure. Go for it :+1:

**Comment by sakshee-19** [comment]
@AdiChat  As far as I understood the issue. For each query term available in tags.json there will be its title and description, subsections of each query will contain different sites(sources of data) and description of sites.  `grand-section` of each query will contain links, description of information related with `query` of the site(sources of data).

Please clarify what is `credit-link` and `tag` here and please explain more about the `grand_section`. 
Do we need to use APIs for every term in different sites and store them in `.json` file? And the defined functions to update `.json` file will be added into update folder?(Since there will be no need to fetch data again and again everytime else `file` needed to be updated).

**Comment by AdiChat** [comment]
This is independent of `tags.json`. You can think of this as a way to include lists in readmes like [this](https://github.com/OpenGenus/Best-student-discount-services) in search results. 

Considering the readme in the example, the sub_sections will be `Collective discounts`, `Electronic devices`, `Productivity apps` and others. `GitHub Student Developer Pack`, `Student Advantage Card` and others will be part of grand_section under the `Collective discounts` subsection. Assume that there will be only one level of nesting that is the `software` section in our example must be simplified in our json file. 

For searching, we will use the tags fields. We may include another field `collective tags` that will include tags of all sections to facilitate searching. This field should be compared with the search term to provide appropriate results. 

`tags` are the keywords for that particular resource. Having only the root tag will serve the purpose, so, inner tags may be removed. For instance, for subsection `Collective discounts`, the tags that will be included in the root tag will be [`collective discounts`, `github student developer pack`, ...]. 

`credit-link` is the link to the resource from which the list has been prepared. In this case, the link will be `https://github.com/OpenGenus/Best-student-discount-services`. 

No external APIs will be required and the json files will be updated manually. 

So, the steps will include preparing a sample JSON file (say L1) (consider the above readme), setup routing and view for the JSON list (keep in mind that process of adding further lists must be simple), prepare a list (say L2) of available lists (L1) (already included as JSON files) and corresponding tags and develop a mechanism to search the above list L2 to find and include appropriate results. 

For the list L2, it can be maintained manually or through code as well.

**Comment by sakshee-19** [comment]
@AdiChat  Sorry for the delay, is this [structure](https://jsoneditoronline.org/?id=7ecf1b5fa3a36ae99129d0849b57df85) is fine for `best Resources to Learn`?
