### ISSUE TITLE
Incorrect Links for Algorithms github code

### ISSUE THREAD

**Issue by itaditya** [OpenGenus/cosmos-search#19]
Go to http://search.opengenus.org/query/?q=byte

The first search result would be bit-manipulation/byte_swapper . 
Click on solution dropdown and then on ByteSwapper.java .
It will take you to an incorrect link i.e. https://github.com/OpenGenus/cosmos/blob/master/code/bit-manipulation/byte-swapper/ByteSwapper.java

But it should be https://github.com/OpenGenus/cosmos/blob/master/code/bit-manipulation/byte_swapper/ByteSwapper.java

**Comment by itaditya** [comment]
Notice the incorrect hyphen instead of underscore in the byte and swapper

**Comment by AdiChat** [comment]
Thanks for reporting this :+1:

The app has been updated with a new search algorithm and updated data.

It looks like that our update system has not been correctly configured on the server. We expected all changes to be reflected automatically. We will look into this. 

Sorry for the inconvenience caused. We hope to make the experience better.

**Comment by AdiChat** [comment]
The update feature is working now as well 👍

**Comment by itaditya** [comment]
Great
