### ISSUE TITLE
Random pre-filled search bar 

### ISSUE THREAD

**Issue by AdiChat** [OpenGenus/cosmos-search#21]
This is a:
- [ ] bug report
- [x] feature request

**Description**:

Randomly load a search term to aid the user to move further. User may be a beginner or may be at a loss of search terms. 
This is aid anyone to randomly learn a topic.

For instance, the search bar may be pre-filled with a search term say `binary search`. For this point, user will have two options:
* Press enter to explore the randomly selected topic
* Enter the search term user is thinking of.

This requires to pick up a folder name from the [`metadata.json`](https://github.com/OpenGenus/cosmos-search/blob/master/metadata.json) and display it is the search bar in an appropriate format.

**Comment by Pl4gue** [comment]
:+1: @AdiChat Will work on that!

**Comment by AdiChat** [comment]
Great 👍 Go for it.

**Comment by ankan17** [comment]
Is this issue still available? I'd like to work on the issue

**Comment by AdiChat** [comment]
This feature can be achieved by creating the list of tags and randomly selecting a tag. See issue #39 

@ankan17 you may attempt creating the list of tags as it is a preliminary step towards this feature. 👍
