### ISSUE TITLE
Code and settings should be separate

### ISSUE THREAD

**Issue by ankan17** [OpenGenus/cosmos-search#36]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request

**Description**:

It is usually a good idea in a Django project to keep the settings separately and not commit those along with the code in the settings.py file (e.g., the SECRET_KEY and ALLOWED_HOSTS, etc.)

**Expected Behavior**:

The settings should be separated from the code in settings.py file. Python Decouple is a great module for this purpose.

**Actual Behavior**:

Code is not separated from settings.

**Steps to Reproduce**:

Just see the settings.py file. It has SECRET_KEY and other important settings committed, which by convention, should not be committed.

**Screenshots (if any)**:

**Would you like to work on this issue?**
- [x] Yes, definitely
- [ ] No

**Comment by ankan17** [comment]
@AdiChat Should I go forward with this issue?

**Comment by AdiChat** [comment]
Yes, this seems to be important. Go for it 👍
