### ISSUE TITLE
Display code in search engine instead of redirecting 

### ISSUE THREAD

**Issue by AdiChat** [OpenGenus/cosmos-search#37]
**I'm submitting a:** 
- [ ] bug report
- [x] feature request

**Description**:

Instead of redirecting to GitHub for every code result, we can fetch the code from the server and display it in a new page. 

The code base (that is Cosmos) is maintained at the server side as a part of the meta-data update process. You may, also, fetch the raw code data from GitHub (instead of server) if convenient. 

Consider a code for `linear search` having a path `code/search/src/linear_search/linear_search.rs`. Currently, we direct the user to [this url](https://github.com/OpenGenus/cosmos/blob/master/code/search/src/linear_search/linear_search.rs) but the target is to direct the user to an url like `search.opengenus.org/code/search/src/linear_search/linear_search.rs` or `search.opengenus.org/code?q=search/src/linear_search/linear_search.rs` which will render the code.

If the users can view the code within the search engine, then the _user retention rate_ will be increased and the learning process can be _centralized_ to Cosmos-Search. You need to use an appropriate syntax highlighter (like prism.js) for this feature.

**Comment by shefalimsr** [comment]
I would like to work on this.

**Comment by AdiChat** [comment]
Sure. @shefalimsr Go for it 👍

**Comment by vaibhavsingh97** [comment]
@shefalimsr What approach you are going to use? As Scrapping content and presenting code to user is a bad idea. Also, what I think if we have a backend server is to cache the content and then just make an AJAX request and present code to user.

**Comment by AdiChat** [comment]
Yes, scrapping should not be considered as an option as this is inefficient and is heavily tied to the current GitHub UI. 

The code can be fetched from the backend server or getting the raw data from GitHub. 👍

**Comment by sakshee-19** [comment]
@AdiChat While opening a code in search results, instead of displaying it in `Search Engine` it is redirecting to Github Code Link. I tried for terms `sort`, `round robin` and `heap sort`
