### ISSUE TITLE
Add ability to share a page

### ISSUE THREAD

**Issue by AdiChat** [OpenGenus/cosmos-search#38]
**I'm submitting a:**  
- [ ] bug report
- [x] feature request

**Description**:

Incorporate the ability to share a page/ search result to social media platforms. The sharing icons may appear below the search bar that is adjacent to the result information (`Showing 1 results for: linear search` for search term `linear search`).

Initially, you may support 3 platforms namely: Twitter, Google+ and Facebook.

This will be a convenient feature to share a result with the user's community and will be a small step towards moving searching to social which is one of our core missions.

**Comment by sakshee-19** [comment]
Do we want to share code of the topic searched or the whole page resulted after searching ? And linkedIn can also be added ? @AdiChat

**Comment by sakshee-19** [comment]
@AdiChat I have included sharing option. It is looking like shown in screenshot. Social media sharing function is working fine. Would you suggest some change in front end.
![screenshot from 2018-02-12 12-15-52](https://user-images.githubusercontent.com/25522394/36085819-9406f974-0fee-11e8-94c0-71ae9ad279b4.png)

**Comment by sakshee-19** [comment]
@AdiChat I think this is more suitable
![screenshot from 2018-02-12 15-10-53](https://user-images.githubusercontent.com/25522394/36090696-5ef0f14a-1007-11e8-8c11-7629b9ac60b3.png)
