### ISSUE TITLE
Generate the list of tags

### ISSUE THREAD

**Issue by AdiChat** [OpenGenus/cosmos-search#39]
**I'm submitting a:**  
- [ ] bug report
- [x] feature request

**Description**:

Create a list of tags that will help in developing several other features. To create the list of tags, you may use the `folder name` as a tag and dynamically, generate the list of tags.
Consider the following path: `code/search/src/linear_search`:For this path, we will get two tags `search` and `linear search`. 

Just like the `meta-data`, the list of tags is expected to be stored in a similar format for further use.

This will give us the ability to organize our search results in a better way.

**Comment by ankan17** [comment]
Should I use the metadata.json file as a source for the list of tags?

**Comment by AdiChat** [comment]
Yes, you can use `metadata.json` as a source to generate the list of tags. 👍
