### ISSUE TITLE
Real-time search suggestions

### ISSUE THREAD

**Issue by AdiChat** [OpenGenus/cosmos-search#40]
**I'm submitting a:**  
- [ ] bug report
- [x] feature request

**Description**:

Using the list of tags, give user real-time search suggestions as the user types. 
The suggestions will contain results from the list of tags and can be generated by string matching. 

Consider the user types `l` in the search bar, then the suggestions will be: `longest_palindrome sequence`, `Longest Bitonic Sequence`, `longest increasing sequence`, `Longest Increasing Subsequence`, ... , `linear programming`, `linear search` and many others.
As the user goes on to type the next letter (that is `i`), then the suggestions are reduced to `linear programming`, `linear search` and others.

Also, note that we may display only 10 real-time suggestions which are randomly selected from the list of suggestions. 

This feature is dependant on the feature mentioned in the previous issue #39 (which must be done first ideally)

This feature will enhance the user experience and will aid learners in discovering new topics and aid faster search.

**Comment by sakshee-19** [comment]
I would like to work on it. @AdiChat

**Comment by sakshee-19** [comment]
It seems you have only generated list and the whole issue is not solved yet in your PR @ankan17 . As, I have already made progress into this issue can I take this further. I have almost done resolved the issue. @adichat @ankan17

**Comment by ankan17** [comment]
I have not yet sent a PR for this issue because the original issue on which it is based has not been merged yet. Doing work on it at this point will create merge conflicts. If you want to work on it, go ahead.

**Comment by sakshee-19** [comment]
@AdiChat @Pl4gue  I have added the feature. But I want to ask weather we should restrict the no of suggestions or not. In the screenshot, it is showing all the possible tags containing ```substring``` written in ```search bar```. Suggestions required :) 
![screenshot from 2018-02-17 10-18-29](https://user-images.githubusercontent.com/25522394/36338112-99db4e54-13cc-11e8-8457-65cd059e6aa4.png)
![screenshot from 2018-02-17 10-25-22](https://user-images.githubusercontent.com/25522394/36338127-e624635e-13cc-11e8-899d-178f5b72bea2.png)

**Comment by Pl4gue** [comment]
Great work, thanks @sakshee-19 !
However, I think that your suggestions container kind of blocks the users' view.
Maybe limit it to the first 6/7.

**Comment by AdiChat** [comment]
@sakshee-19 You may show 5 suggestions that are randomly chosen from the suggestion results set. 

Instead of the typed word being a substring, you may look for strings that begin with the typed word/ letters. This will look more natural to the user and will be a minor change. :smile: 

Feel free to send a pull request anytime. :+1:

**Comment by Pl4gue** [comment]
I would prefer how it is now... because I would like all sorts to be shown on query "sort" (in your case it wouldn't show quick_sort i.e. @AdiChat

**Comment by AdiChat** [comment]
We. already, provide suggestions for a particular search. 

This feature is to aid user to go in one direction of learning whereas the suggestions feature (which already exists in our search engine) provides multiple paths of learning. 

Even in this case, keyword `sort` will provide various sorting algorithms as typed suggestions as it will match the second word. So, when a user intends to type `linear search`, he/she will not be interested in `binary search` but may be interested after going through `linear search` results. 

So, this feature should look for strings that begin with the typed word/ letters to provide one focused path of learning. :+1:

**Comment by Pl4gue** [comment]
Alright 👍 @AdiChat
