### ISSUE TITLE
__pycache__ should be in .gitignore

### ISSUE THREAD

**Issue by ankan17** [OpenGenus/cosmos-search#42]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request

**Description**:

__pycache__ should be in .gitignore. It is not meant to be in the git repo.

**Expected Behavior**:

__pycache__ should be in .gitignore and not in the repo

**Actual Behavior**:

__pycache__ is not in .gitignore.

**Steps to Reproduce**:

Check the cosmos-search folder.

**Screenshots (if any)**:

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

**Comment by ankan17** [comment]
__pycache__ folder contains byte-code which is not meant to be committed @AdiChat

**Comment by Pl4gue** [comment]
Pycache is already in gitignore, closing this issue
