### ISSUE TITLE
Page not found error while opening code files

### ISSUE THREAD

**Issue by sakshee-19** [OpenGenus/cosmos-search#44]
**I'm submitting a ...** 
- [X] bug report
- [ ] feature request

**Description**:
There is bug in redirecting link of code files.  It shows "error 404 Web Page in not found".

**Expected Behaviour**:
When we click on any code shown in solution drop down, it should redirect to GitHub page where the code is present.  
 
**Actual Behaviour**:
On clicking to the code, it is showing page not found error.

**Steps to Reproduce**:
Search for any code in search-bar
From solutions drop down menu try to open any code.

**Screenshots **:
![screenshot from 2018-02-11 19-22-08](https://user-images.githubusercontent.com/25522394/36074085-0d76ee88-0f61-11e8-9b46-95c58ba5e562.png)

**Would you like to work on this issue?**
- [X] Yes
- [ ] No

**Comment by sakshee-19** [comment]
@AdiChat  can I go ahead with this issue?

**Comment by AdiChat** [comment]
I guess this error came up while running Cosmos-Search locally. This is concerned with the fact that we have not updated the `metadata.json` (in this repository) for some time while there have been structural changes in Cosmos. 

You need to update the metadata. Take a look [here](https://github.com/OpenGenus/cosmos-search/blob/master/update/views.py#L7). Go for it 👍

**Comment by sakshee-19** [comment]
@AdiChat The metadata received to the server does not contain the key ```HTTP_X_HUB_SIGNATURE```. I guess this is due to the fact that I am running on localhost. Could you please help me out?

**Comment by sakshee-19** [comment]
@AdiChat This problem has been fixed by PR #39.
