### ISSUE TITLE
Should we add a linting tool?

### ISSUE THREAD

**Issue by ankan17** [OpenGenus/cosmos-search#49]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request

**Description**:

A linting tool like flake8 is necessary to have the code live in the repository in a proper way and to have a good code base.

**Expected Behavior**:

A linting tool should be implemented and the current linting issue should be resolved.

**Actual Behavior**:

No linting tool, so the code doesn't follow PEP8 guidelines

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

**Comment by ankan17** [comment]
@AdiChat What do you think?? :)

**Comment by AdiChat** [comment]
Yes, it is nice to have a linting tool added. 👍
