### ISSUE TITLE
static_root is not defined

### ISSUE THREAD

**Issue by sakshee-19** [OpenGenus/cosmos-search#51]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Description**:
There is no ```static_root``` defined. Hence, it is creating problem whenever we are running command ```python manage.py collectstatic``` .

**Expected Behavior**:
The collectstatic management command should collect static files into the mentioned directory.

**Actual Behavior**:
![screenshot from 2018-02-13 18-55-17](https://user-images.githubusercontent.com/25522394/36160544-74b87240-1107-11e8-8c17-672d48b6eb01.png)

**Steps to Reproduce**:
* run the command ```python manage.py collectstatic```

**Would you like to work on this issue?**
- [X] Yes
- [ ] No

**Comment by sakshee-19** [comment]
@AdiChat should I go ahead with this issue?

**Comment by AdiChat** [comment]
Sure. Explore this issue 👍
