### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by pragyach** [OpenGenus/cosmos-search#55]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request

**Description**:

If I go for  searching  anything there is no back button on the page to return to previous or home page.

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

**Comment by Pl4gue** [comment]
Nice idea, but I however don't really get the benefit. The user can just press the browser back button...

**Comment by pragyach** [comment]
Yes I agree with your reply.So in addition to back button concept we can store user's search history similar to you tube,Chrome etc in order to make cosmos search more user specific.For doing this we may need to ask user to sign in with gmail or something else.

**Comment by AdiChat** [comment]
Hi @pragyach :v:
User authentication and history are on our plan. If we store user history, we can create exciting new features like personalized learning paths, develop the mental model of the user based on knowledge gained and many more. 🎉 

For this, the basic outlay is to create the authentication system and store the search history. You can work on this. 👍 

Feel free to get in touch if you need any help. 😄

**Comment by pragyach** [comment]
Thank you @AdiChat  you made me more clear about this feature. I will start with basic outlay to create authentication system for google sign in first.

**Comment by AdiChat** [comment]
Sure @pragyach Go for it.  Keep us updated on your progress :+1:

**Comment by Pl4gue** [comment]
Well I will close this issue now, kindly open up a new issue for authentication which we can then assign to you :+1: :smile: @pragyach
