### ISSUE TITLE
Add computational power

### ISSUE THREAD

**Issue by AdiChat** [OpenGenus/cosmos-search#58]
**I'm submitting a:**  
- [ ] bug report
- [x] feature request 🏆 

**Description**:

We must provide some _computational 💻 power_ to the search engine. We must define a set of search keyword formats and on matching, we must trigger the corresponding computation and present the result.
For instance, if the user searches `2*5` or `2 X 5`, we must return 10. 📅 

Basic operations such as addition, subtraction, multiplication, division, modulus, square root, trigonometric operations and others can be supported in the initial version. 

Having computational power will improve the usability of the engine and will be used as a basis for further exciting features. 

Let us know if you would like to work on this. 👍

**Comment by sakshee-19** [comment]
I would like to work on it.

**Comment by AdiChat** [comment]
Sure. Go for it :+1:

**Comment by Pl4gue** [comment]
Assigned it to you @sakshee-19 :+1:

**Comment by sakshee-19** [comment]
@AdiChat @Pl4gue There is no secret key in ```settings.py``` file. Now it has moved into the ```.env_example``` and it is mentioned that ARandomSecretKey. Now when I am trying to run ```manage.py runserver``` then it asked me that there is no secret key in ```settings.py``` . Please illustrate me how I should connect my``` .env_example``` file. I am attaching a screenshot of my problem. 
![screenshot from 2018-02-24 13-34-14](https://user-images.githubusercontent.com/25522394/36627375-a89aafca-1967-11e8-95d8-5649dff9cc55.png)

**Comment by AdiChat** [comment]
@sakshee-19 The problem is the environmental variables have not been set. 

Did you try `cp .env.example .env`? 
You may additionally, set the environmental files at `.bashrc`. Include the following lines at the end of the file:
```
export SECRET_KEY='ARandomSecretKey'
export DEBUG='False'
export ALLOWED_HOSTS='localhost'
export GITHUB_WEBHOOK_SECRET='b8049cbcf55b2ee998c9be302220064757421f85'
```
Then, type the command `source ~/.bashrc` to reload it. 

The issue must be resolved at this point. Let us know if it worked. :+1:

**Comment by sakshee-19** [comment]
@AdiChat  Thanks, It is working using ```cp .env.example .env``` . We should include it in ```README.md```.

**Comment by AdiChat** [comment]
You may display the result of the calculation along with the expression above the results. :+1:

**Comment by sakshee-19** [comment]
I am working on front end part of calculator. I will commit the code as soon as possible.
