### ISSUE TITLE
Topic Tags on Main page

### ISSUE THREAD

**Issue by pragyach** [OpenGenus/cosmos-search#63]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request

**Description**:
Whenever user enters cosmos-search he/she is not aware about topics like bit manipulation,AI etc.So in order to make user's learning path more smooth we can display topics on main page.

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

**Comment by AdiChat** [comment]
Yes, this will aid the user in searching.

You may display a limited number of tags (say 10) under the search bar and point to another page that will list all tags. You must use the tags that are present in `tags.json`. The tags (under the search bar) may be randomly selected for now. Ideally, this should be related to the current search term. 

You may work on this. Keep us updated on your progress. :+1:

**Comment by pragyach** [comment]
Okay I understood your point.So in order to redirect to next page I will add one more tag after these 10 tags "More..." and then link new page with this button.Is this what you wish to be done? @AdiChat

**Comment by AdiChat** [comment]
Yes, this should be good. :+1:
