### ISSUE TITLE
Section to add code to missing algorithm.

### ISSUE THREAD

**Issue by AneriMehta** [OpenGenus/cosmos-search#64]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request

**Description**:
A section can be provided where code to some missing algorithms can be added as well as others can upvote or downvote this code or comment if there is any bug present.

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

**Comment by pragyach** [comment]
I think that will be covered in issue#62.

**Comment by AneriMehta** [comment]
Okay, @pragyach.
