### ISSUE TITLE
Remove test cases from search results

### ISSUE THREAD

**Issue by arnavb** [OpenGenus/cosmos-search#67]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request

**Description**:

If I search up something such as test in the search, I get results that include the testing of the algorithms in cosmos. Users don't really care about this, so such results should be filtered out.

**Expected Behavior**:

N/A

**Actual Behavior**:

You see test results

**Steps to Reproduce**:

- Search up test in the search. Some results are from the test folder of cosmos.

**Screenshots (if any)**:

**Would you like to work on this issue?**
- [ ] Yes
- [x] No

**Comment by pragyach** [comment]
I also think giving output for testing for algorithms will be out of the context result.If this is done intentionally @AdiChat  then instead we can add it as feature on main page for testing code for  algorithms.Then on clicking to this he/she will be rendered to page which simply contain list of testing algorithms with names.
![cosm](https://user-images.githubusercontent.com/20520778/36651976-eabd42bc-1ad1-11e8-86cd-b528213a137c.png)
If this is find suitable and @arnavb  is not willing to fix this,I would like to work on this.
