### ISSUE TITLE
 Adding .editorconfig to maintain consistent coding style across whole project.

### ISSUE THREAD

**Issue by Shweta4321** [OpenGenus/cosmos-search#68]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [X] feature request

**Description**:
 - EditorConfig helps to define and maintain consistent coding styles between different editors and IDEs.
- It will help to bring consistency in the project, and reinforces fixed and valid set of styles to be followed across, while making any changes in the project.

**Expected Behavior**:
Following specific set of coding style for having consistency across the whole project.

**Actual Behavior**:

- Currently there isn't any standard coding style getting followed.
- When developers propose any changes in the project it brings inconsistency to the project, since every developer has his/her own convention of coding style.

**Would you like to work on this issue?**
- [X] Yes
- [ ] No

**Comment by Shweta4321** [comment]
@AdiChat Shall I proceed further? Please suggest.

**Comment by AdiChat** [comment]
Sure. Go for it :+1:
