### ISSUE TITLE
The 'Travis' build is failing

### ISSUE THREAD

**Issue by Shweta4321** [OpenGenus/cosmos-search#85]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request

**Description**:
While we working with database the `python manage.py test ` is not executing.
The `Travis` build is failing because there are no commands regarding `makemigrations` and `migrate` in travis.yml. 
**Expected Behavior**:

![screenshot from 2018-03-04 01-45-34](https://user-images.githubusercontent.com/23321431/36991711-8d5332e6-20ce-11e8-9857-3d216d642e3e.png)
**Actual Behavior**:
![screenshot from 2018-03-04 01-45-05](https://user-images.githubusercontent.com/23321431/36991705-8a9b1e9c-20ce-11e8-80b5-17c8277cba45.png)
**Would you like to work on this issue?**
- [X] Yes
- [ ] No

**Comment by Shweta4321** [comment]
@AdiChat Shall i proceed?

**Comment by AdiChat** [comment]
Sure. Go for it :+1:
