### ISSUE TITLE
The search box needs to be cleared before giving a new query

### ISSUE THREAD

**Issue by sarvanideekshitula** [OpenGenus/cosmos-search#88]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request

**Description**:
We have to clear search box every time before entering a new query.

**Expected Behavior**:
The search box should be cleared if the user wants to enter a different query.

**Actual Behavior**:
The search box is filled with the suggestion which the user has to clear every time.

**Steps to Reproduce**:
The suggestion should be pre-selected ( like google search bar ) so that the search box is cleared and enables the user to give a new query or if the user presses enter, the page gets directed to the suggestion. 

**Screenshots (if any)**:

**Would you like to work on this issue?**
- [x] Yes
- [ ] No

**Comment by AdiChat** [comment]
Yes, when the user types the pre-filled suggestion must be cleared. Go for it :+1:
